-
 name: docker instalation
 hosts: servers
 become: yes
 tasks:
   - name: docker install
     apt:
       name: docker
       state: latest
     when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
   - name: aws_cli install
     apt:
       name: awscli
       state: latest
     when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'    
